language: elixir
elixir:
- 1.10.2
otp_release:
- 22.1.8
addons:
  postgresql: '9.5'
cache:
  directories:
  - _build
  - deps
script:
- mix do deps.get, coveralls.json
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - MIX_ENV=test
