language: elixir
elixir:
- 1.1
otp_release:
- 22.1.8
addons:
  postgresql: '9.5'
cache:
  directories:
  - _build
  - deps
script:
- mix do deps.get, compile --warnings-as-errors, coveralls.json
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - MIX_ENV=test
  - AWS_REGION=eu-west-1
  - LIVEVIEW_SIGNING_SALT=EverythingIsAwesome
  - secure: r7sfZLNfOmgVcGer4R2OKQgjzIrCuTINK7v241ZG6Q4MYaAhrSobTTDsbQde6jHvGtxmFy3mhkdZcKpjPHotPUYGi58i4TpGzZdMBQdQC6ee5Zfyg4d40Tyet4P10BPMLfJZiz9mH2xwcPJmWVTxyZV6erDnewdSahKr3ITLKB/Rc5Deyxk4sP2yx+K8u1T0us8Wc4T1H94roRqsLeDPIsxXLsMh5o6BgEp4b4pLXgzWQXVNu0EtQ2M0CXVPsopIfSVlNpRRTETBW8omAGcEoGniv6wKEagPOcUhqzxqxxeRlsuwhFTfE0/O8LyYuuPq1uS9D5STVCh7+xK4SyNYWR1oT+dSIyNYbRjVkKNOL+4S1D97ZLJ5fEFwbxvLpeVZTB1X4+6OApNNe7Gj/pPR6bd9mNZZx5joSOKA45TUNkKgBBXnZ1CAbN/7HuGMaE0Gf0cLsAIpY2aoSlanObq09F08W9W7SYgzGX25SZjgmVZKIN/4GMe1VXLaXvhI70iGwtEHbngqZBqfrvmiqkBZfOiZ22IoGZfv1rpaDr3FtZHstrR9A+ygW34mwSi5wJHIpIC7ZECqB5UVtzK+gQHUd54e3eCWSLsUJg7hgzTiL9yAMm5KiPBWB9ihpqHZRDmdwX45waD8N00slqaIiakeEuL4X0ADomQDKgbziko5Jdw=
  - secure: Eac4FxyTs0KZXsRLpcCg62v8J9y8cPYSoXNqbPCna+SjgPX4ZW1zCefZ7RBVdUu7mzd5fyp6AS0cCIUAdqBkMLCxjO9c+gw0ZeRBBfOAaQ5STL7ESB4hmQ/wnPRK9jgsyVhgSQ+mV2bO6RZ+0vs7a0D27R3ModXSJGjSf5J/riL29/yuCIvcvQhjgAM7iEMI81wKFHKsCb1cCasKA6WApzfy4HkNH3eygCf+Vqe7skvajNhuM0hpmjqOBiSghfjWDuZQyp4I/u6Vj/o/xaPhfS01Z/iy+AkWm9jNLGxAMQ6MM3n8cSvzOw9EOHwMUhMEKIWMIBLk5YBKZpEp9TFlqUbtH1rO2XSVC9Y3/QR2DBpU/sOO+1Ei40nmEJ5xw9nwA1Tn9AtQuN1kf8jzQi3Pzky+Ke6sljzPDpkDk6yEY59iTc2XXFM83Z4aC2wfDolYWb+p1NS7ivdP3DFvkz4qPz1ZO6UMaTEz6mPzWiuhVGmaYE9ayXG1e2GlmnSoc7k41TlrVho3naIq/jLRF9WkQbUHLd0S7jWwLm+Xj4gN0JJi9klhL+tB1pPIO7cd7f7oiZray2JUpWW04vnfaM+WN41nJOyJv7a6NxVujQMCgTR4ev7njDNWzX1ZV3gYYMKTPPtuIuCc03QKjJWjowxuH/PPpePSXE2A8nRC4nXv8SY=
  - secure: HCuZeq+RDTXZFmk/XSr8mLtNjRPkksi/SxrE+VdZ4Sj12AZ/XC1lbBzwvhqVRnucW1Hjj720c8/dFbiXaRYFKvt/QEgnI8y9x+Roijy2w4S98Q051krmMMrD539iQq/hiu82u/VWWVS5qqzTB6kZz7OeA/w+gI2fb162rhiydM9sk3ot5NMGPRyEASPqIdflq+cVIi/ixvHUF9ke9I82Td2TKYi+ILpeOqdP17Viwdw1+4fTjZU1Xzm7eaKPN0fSEjDk+J1jEgRDPWiT1c8IEVJCobAp+h3fnytfru5sxgiUJolaYJo5b7RtY8ay/6q5P4LsRqrjbpTAMGohqFqfFyWdVISfGpSoxNTQzmogGcKPLHZlSqn4G4rIrhzDNYkwryAowgHZtzPCbUQNMxfLtEWx7EjWglHQf4ohQ8lr264q9+g9RPF2BljXWHH+8CaAhxT1pf8IYtSdok4FQOdIRZLnUFLJ5WUhrq7+ClLDWtQMvWCpU74/FHH/kpZdLkrPTlp7U8TwcCnZEPuVIQ+7/sdPUnum9/WwPaYtcd+JeJhfHsJ0xWcCahXHj2AZ0TNqFqfosgrccTmkGlhONPwSpoeWp+54KKWORAQ0+mZs6nuRbp5/kWKu2neU6KR/7IaQnYKfISLtePpRVpZLYMbUo0ZTR8baERGrL2Cg1SW1ayQ=
