language: elixir
elixir:
- 1.10.2
addons: # ensure that Travis-CI provisions a DB for our test:
  postgresql: '9.5'
cache:
  directories:
  - _build
  - deps
script:
- mix do deps.get, compile --warnings-as-errors, coveralls.json
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - MIX_ENV=test
  - AWS_REGION=eu-west-1
